services:
  db:
    image: postgres:16
    container_name: employees_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: employees
    ports:
      - "5433:5432"
    volumes:
      - employees_db_data:/var/lib/postgresql/data

volumes:
  employees_db_data:
